name: Build ocaria2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Bulid:
    name: Build ${{ matrix.name }} ${{matrix.arch}}
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        include:
          - name: 'Ariangwke'
            arch: 'x86'
            platfromType: 0
            ui: 0
          - name: 'Ariangwke'
            arch: 'x64'
            platfromType: 1
            ui: 0
          - name: 'AriangNative'
            arch: 'x86'
            platfromType: 0
            ui: 1
          - name: 'AriangNative'
            arch: 'x64'
            platfromType: 1
            ui: 1
          - name: 'Ariang'
            arch: 'x86'
            platfromType: 0
            ui: 2
          - name: 'Ariang'
            arch: 'x64'
            platfromType: 1
            ui: 2
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: ${{ matrix.arch }}

    - name: Install requirements
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install git+https://github.com/pyinstaller/pyinstaller.git
          pip install pyunpack patool requests
    
    - name: Get dependencies aria2 and ariangwke
      run: python3 .\.ci\dependency.py ${{ matrix.platfromType }} ${{ matrix.ui }}
    
    - name: Build with pyinstaller for ${{ matrix.name }} ${{matrix.arch}}
      run: pyinstaller ocaria2.spec

    - name: 7z output files
      run: 7z a -t7z -mx=9 build.7z ./dist/
  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package_windows_${{ matrix.name }}_${{ matrix.arch }}
        path: ./build.7z   
    
    